# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-04 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=400)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_comments', models.IntegerField(default=0)),
                ('author', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(default='picture_folder/chipeenss.jpg', on_delete=django.db.models.deletion.CASCADE, to='instagram.Image')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
